import os.path
import sys
import unittest

sys.path.insert(0, os.path.abspath('..'))
from plugins.generic import unpack_obfuscatorhtml  # noqa


class TestObfuscatorHTML(unittest.TestCase):

    def test_unpack_obfuscatorhtml(self):
        javascript_input = """<script>var MLF = ""; var ncR = ["aE5mNjEyNDcxOThCemg=", "T1lCNjEyNDcxNzFmWUg=", "eVFINjEyNDcyMDZNYlA=",
"QWdjNjEyNDcyMTdQSWw=", "YUpBNjEyNDcyMDVTdGk=",
"V3BsNjEyNDcyMjJHUkU=", "QllpNjEyNDcyMjdJblc=", "Z1RoNjEyNDcyMThWdEY=",
"YnNQNjEyNDcyMDdGT3I=", "eU5sNjEyNDcxNzBUdGM=",
"enB0NjEyNDcyNDJ4blQ=",
"cFVYNjEyNDcyNTRWRm8=", "UWZXNjEyNDcyNDdlS3g=",
"WkJLNjEyNDcyNDZoWG0=",
"cVVsNjEyNDcyMDB5YWc=", "elZxNjEyNDcxOThORFE=", "endXNjEyNDcyNDJiU2U=", "b3Z5NjEyNDcyNTRiWHo=", "VXZjNjEyNDcyNDdIaFQ=",
"cUdvNjEyNDcyNDZjeXQ=", "bU9zNjEyNDcyMDBsRGI=",
"SkVTNjEyNDcxOThvaHU=",
"Rlp6NjEyNDcyMzZYWnM=",
"cUVNNjEyNDcyNDlkTGY=", "eHhJNjEyNDcyMzhhVlo=", "Z0tZNjEyNDcyNTlWaHY=", "Unp0NjEyNDcyMDBvS2M=", "a3NqNjEyNDcxOTh1WGg=", "bVBkNjEyNDcyNTNVY2s=",
"bG5qNjEyNDcyMzdZSmc=",
"Q2lBNjEyNDcyNTJsRXk=",
"UXpwNjEyNDcyNDN0cWc=",
"cnlPNjEyNDcyNTBmZFk=",
"U1JlNjEyNDcyNTROVkg=", "b2RsNjEyNDcyMDBKWmI=", "QmtwNjEyNDcxNzJSbHQ=",
"c3NlNjEyNDcyMTJNeHU=",
"Y2hYNjEyNDcyMzVLbVQ=",
"d2pYNjEyNDcyNTZiUkc=", "eGZ2NjEyNDcyMzVHbmQ=", "VGpJNjEyNDcyMjFKQUo=", "QmFKNjEyNDcyMzdGYW0=", "RnhyNjEyNDcyNTJudkg=",
"SGVBNjEyNDcyNDNSc2I=",
"ZWVpNjEyNDcyNTBRYkg=", "dkRyNjEyNDcyNTRvdVo=",
"bm5iNjEyNDcxNzJmY3Y=", "TFJhNjEyNDcxOTdmbGM=",
"emhRNjEyNDcxOThhdHg=", "YnRmNjEyNDcxODVOYW8=",
"S3p5NjEyNDcyNTNQT2w=", "bExRNjEyNDcyMzdhamg=", "WmVVNjEyNDcyNTJ1dWU=", "U0t0NjEyNDcyNDN6U0c=",
"QVduNjEyNDcyNTBLZ3E=", "ekphNjEyNDcyNTRSYlY=",
"T3VYNjEyNDcyMDBET1o=",
"a0ZDNjEyNDcxOThzVFI=",
"cUprNjEyNDcxODVVTHY=", "eWtWNjEyNDcyMzZpeFk=", "T1RFNjEyNDcyNDltUEQ=",
"aERmNjEyNDcyMzhrZEQ=",
"SXRxNjEyNDcyNTlhUVk=",
"YUFvNjEyNDcyMDBEWXU=", "UGNGNjEyNDcxOThIeHo=",
"SUltNjEyNDcxODVsbXc=",
"d0pDNjEyNDcyNDJKc3g=", "SlVkNjEyNDcyNTRHRHc=", "bGtTNjEyNDcyNDdncWU=", "Z1VhNjEyNDcyNDZrdlo=", "cGdkNjEyNDcyMDBWV0g=", "empTNjEyNDcxNTFiaWM=",
"VEtqNjEyNDcxNDh0dGE=",
]; ncR.forEach(function PiX(value) { MLF += String.fromCharCode(parseInt(atob(value).replace(/\\D/g,'')) - 61247138); } ); document.write(decodeURIComponent(escape(MLF))); </script>"""
        javascript_output = """<!DOCTYPE html><html><body><script>"JavaScript";</script></body></html>\r\n"""
        self.assertEqual(unpack_obfuscatorhtml(javascript_input), javascript_output)

    def test_unpack_obfuscatorhtml_script_with_text(self):
        javascript_input = """<script "script with text">var aKG = ""; var uPf = ["a2ZmNDIwMDc5ODZlTnE=",
"RWJlNDIwMDc5NTlHRnk=",
"UUtMNDIwMDc5OTRiQWU=",
"ZnVrNDIwMDgwMDVRdE8=",
"R2VONDIwMDc5OTNiWGE=", "WHJNNDIwMDgwMTBIU2c=", "akNVNDIwMDgwMTVzRXY=", "eUlCNDIwMDgwMDZYdnQ=", "RFl0NDIwMDc5OTVPakc=", "V1NYNDIwMDc5NThjTnM=",
"Z1dENDIwMDgwMzBFaFg=",
"anJCNDIwMDgwNDJteHc=",
"d2dRNDIwMDgwMzVhWmI=",
"bVRiNDIwMDgwMzRiQ04=",
"eXJENDIwMDc5ODh6d1M=", "TFRNNDIwMDc5ODZnd2c=",
"SFRENDIwMDgwMzBsYmo=", "QVN3NDIwMDgwNDJYY2I=",
"eWlCNDIwMDgwMzVRWk0=", "dWlxNDIwMDgwMzRQY2Q=",
"b2dwNDIwMDc5ODhRd3A=", "akhqNDIwMDc5ODZ4Um0=",
"ZFVDNDIwMDgwMjRlQ0g=",
"R2xXNDIwMDgwMzdhZXM=", "eVFVNDIwMDgwMjZsc0E=", "ZWhtNDIwMDgwNDdxQWc=", "VGxENDIwMDc5ODh2Ylk=", "cWZYNDIwMDc5ODZndmw=", "YVp1NDIwMDgwNDFWa3U=",
"c1hHNDIwMDgwMjVKZm8=", "eUlpNDIwMDgwNDBTVmY=",
"em9XNDIwMDgwMzFMWno=", "QUxtNDIwMDgwMzhLSUI=",
"bE1GNDIwMDgwNDJ4dGU=",
"TEF2NDIwMDc5NThRYno=", "R0lCNDIwMDgwNDJBc3E=", "bWRtNDIwMDgwNDdLWFU=",
"bmVINDIwMDgwMzhlUWw=", "QUZCNDIwMDgwMjdpRlE=",
"cU5BNDIwMDc5ODdrWGY=",
"VmZZNDIwMDc5NjBLVG4=", "Z2pQNDIwMDgwNDJ5clU=", "aWFaNDIwMDgwMjd4Yk8=",
"WVZKNDIwMDgwNDZYcWI=",
"cURiNDIwMDgwNDJ6QUc=",
"R1FHNDIwMDc5NzNCcEk=", "ZmtrNDIwMDgwMzJXZWo=",
"V0JMNDIwMDgwMjNITVA=", "a0JYNDIwMDgwNDRJZm8=",
"Y0NHNDIwMDgwMjNKdVE=", "R0RKNDIwMDgwNDFoc08=",
"WHZENDIwMDgwMjVJTW8=", "bHhINDIwMDgwNDBiRGo=", "Q0lUNDIwMDgwMzFlSWk=",
"cFJjNDIwMDgwMzh0VWI=", "dWdINDIwMDgwNDJtS0E=",
"b2lCNDIwMDc5NjBRSHc=",
"ZmZsNDIwMDc5ODhVQ0k=", "RnpMNDIwMDc5NjB1c00=", "UlNiNDIwMDgwMDBDbGs=",
"clNDNDIwMDgwMjNaYms=", "cW1kNDIwMDgwNDRlc2s=", "V0pHNDIwMDgwMjNXdHQ=", "SWVlNDIwMDgwMDlMWk0=",
"b05ENDIwMDgwMjVicVg=", "T0JzNDIwMDgwNDBHUWQ=", "aXBGNDIwMDgwMzFGZkc=", "YnNnNDIwMDgwMzhpc2c=", "VlJTNDIwMDgwNDJPSHc=", "dHlvNDIwMDc5NThWQXQ=", "bm5QNDIwMDgwMDJHaFg=", "bFNDNDIwMDgwMzFhakE=", "eVdpNDIwMDgwNDRQeEk=",
"WFZZNDIwMDgwMjd5cVo=", "V25DNDIwMDgwMjVTbmI=",
"WFVtNDIwMDgwMzRJV3E=",
"ck1ONDIwMDgwMzFQR3I=",
"V3N4NDIwMDc5NjBxSVE=", "TnlqNDIwMDc5ODVnWU8=",
"QXlZNDIwMDc5ODZiTU4=", "ZWtoNDIwMDc5NzNjbWU=",
"a3NJNDIwMDgwNDFjUE8=", "TXRMNDIwMDgwMjVoZlg=", "ekdHNDIwMDgwNDBqZFk=", "REZONDIwMDgwMzFWaHM=",
"Z2lGNDIwMDgwMzhFaFA=",
"ek9FNDIwMDgwNDJzek4=", "SElYNDIwMDc5ODhETWo=",
"V2JXNDIwMDc5ODZ0QmY=", "UGFaNDIwMDc5NzNVYWY=",
"eVR5NDIwMDgwMjRab0I=",
"UWtPNDIwMDgwMzdhZFQ=",
"SXFxNDIwMDgwMjZadlA=",
"VEd2NDIwMDgwNDdOcUU=",
"Vm1MNDIwMDc5ODhycnM=",
"S2R3NDIwMDc5ODZ5YVg=", "VkJENDIwMDc5NzN2bUM=", "UUJtNDIwMDgwMzBYUkw=",
"UEZNNDIwMDgwNDJpS1A=",
"RUlYNDIwMDgwMzVIQUQ=", "TmdQNDIwMDgwMzRnVkI=",
"ZE5BNDIwMDc5ODhGcEU=", "TXR2NDIwMDc5MzlpbEU=", "SnFQNDIwMDc5MzZZTkc=",
]; uPf.forEach(function iMn(value) { aKG += String.fromCharCode(parseInt(atob(value).replace(/\\D/g,'')) - 42007926); } ); document.write(decodeURIComponent(escape(aKG))); </script>"""
        javascript_output = """<!DOCTYPE html><html><body><script type="text/javascript">"JavaScript Livecli";</script></body></html>\r\n"""
        self.assertEqual(unpack_obfuscatorhtml(javascript_input), javascript_output)
